//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPortfolioProjects161022.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPSchoolDbPortfolioEntities : DbContext
    {
        public UPSchoolDbPortfolioEntities()
            : base("name=UPSchoolDbPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
        public virtual DbSet<TblServices> TblServices1 { get; set; }
        public virtual DbSet<TblServicesFeature> TblServicesFeatures { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
        public virtual DbSet<TblTestimonial> TblTestimonials { get; set; }
        public virtual DbSet<TblMember> TblMembers { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
    }
}
